### ISSUE TITLE
Header issue

### ISSUE THREAD

**Issue by eko24ive** [Reebay/homework#1]
Here is your header:
![image](https://cloud.githubusercontent.com/assets/25591824/22922763/b312614c-f2a7-11e6-965d-b09dc48dc499.png)

Please fix it's height, padding and add "Project Name".
Use design reference:
![image](https://cloud.githubusercontent.com/assets/25591824/22922779/bf10c20e-f2a7-11e6-9031-45ac236fdfc0.png)

**Comment by Reebay** [comment]
Fixed

**Comment by eko24ive** [comment]
Nicely done !
