### ISSUE TITLE
Centering issue

### ISSUE THREAD

**Issue by eko24ive** [Reebay/homework#3]
Your content isn't aligned to center.
![image](https://cloud.githubusercontent.com/assets/25591824/22922991/66da56ee-f2a8-11e6-9e38-e99a5124b602.png)

Use design reference:
![image](https://cloud.githubusercontent.com/assets/25591824/22923028/8273b044-f2a8-11e6-8cd1-908a30449bb8.png)

**Comment by Reebay** [comment]
Fixed

**Comment by eko24ive** [comment]
Awesome !
