### ISSUE TITLE
Content alignment issue

### ISSUE THREAD

**Issue by eko24ive** [Reebay/homework#4]
Here is your markup:
![image](https://cloud.githubusercontent.com/assets/25591824/22923745/5f504ffc-f2ab-11e6-8d11-65b95ab2efa5.png)

Please align content to the left side, use design reference:
![image](https://cloud.githubusercontent.com/assets/25591824/22923728/55b9c284-f2ab-11e6-8702-b39a2215f5e5.png)

**Comment by Reebay** [comment]
Fixed

**Comment by eko24ive** [comment]
Nice !
