### ISSUE TITLE
Content padding

### ISSUE THREAD

**Issue by eko24ive** [Reebay/homework#5]
![image](https://cloud.githubusercontent.com/assets/25591824/22923796/86c1e4ec-f2ab-11e6-9e33-52f788350e0e.png)

Please increase padding in content blocks, use design reference:
![image](https://cloud.githubusercontent.com/assets/25591824/22923841/9a4cc608-f2ab-11e6-97fe-93c6808d34e3.png)

**Comment by Reebay** [comment]
Fixed

**Comment by eko24ive** [comment]
Indeed !
