### ISSUE TITLE
Footer padding

### ISSUE THREAD

**Issue by eko24ive** [Reebay/homework#6]
![image](https://cloud.githubusercontent.com/assets/25591824/22923858/aa74a690-f2ab-11e6-86de-c355ad928076.png)

Increase footer spacing and padding according to design:
![image](https://cloud.githubusercontent.com/assets/25591824/22923875/bbe809e4-f2ab-11e6-835c-b43e0058b9a0.png)

**Comment by Reebay** [comment]
Fixed

**Comment by eko24ive** [comment]
Good job !
