### ISSUE TITLE
Footer mismatch

### ISSUE THREAD

**Issue by eko24ive** [Reebay/homework#7]
![image](https://cloud.githubusercontent.com/assets/25591824/22923858/aa74a690-f2ab-11e6-86de-c355ad928076.png)

Please provide links to footer, according to design:
![image](https://cloud.githubusercontent.com/assets/25591824/22923875/bbe809e4-f2ab-11e6-835c-b43e0058b9a0.png)

**Comment by Reebay** [comment]
Fixed, but without points before links)

**Comment by eko24ive** [comment]
Please add bullet symbol before each link

**Comment by Reebay** [comment]
This is a good solution? How alternative? Fixed)

**Comment by eko24ive** [comment]
This is acceptable but not the best solution, try do it with `:before` pseudo class

**Comment by Reebay** [comment]
Ohhh yee) Fixed)

**Comment by eko24ive** [comment]
Easy peasy, isn't it ?)
